WebApp/Controllers/UndianController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApp.Data;
using WebApp.Middlewares;
using WebApp.Models;

namespace WebApp.Controllers
{

    [Microsoft.AspNetCore.Authorization.Authorize]
    public class UndianController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IPeriodeService _periodeService;

        public UndianController(ILogger<HomeController> logger, ApplicationDbContext context, IPeriodeService periodeService)
        {
            _logger = logger;
            _context = context;
            _periodeService = periodeService;
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Roles = "admin, administrator")]
        public async Task<IActionResult> Index()
        {
            try
            {
                var active = await _periodeService.ActivePeriode();
                if (active == null)
                    throw new SystemException("Periode Active Belum Ada");
                if (active.Status==false)
                    throw new SystemException("Periode Active Belum Ada");

                var pemenang = _context.Pemenang.Where(x => x.PeriodeId == active.Id)
                    .Include(x=>x.Karyawan).FirstOrDefault();
                if (pemenang != null)
                {
                    ViewBag.Pemenang = pemenang;
                }

                return View();
            }
            catch (Exception ex)
            {
               return BadRequest(ex.Message);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    @* <link  rel="stylesheet" href="~/lib/Montserrat/Montserrat-Regular.css?fonts=roboto-regular" type="text/css" /> *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome5/css/all.css" />
    <link rel="stylesheet" href="~/lib/Chartjs/Chart.css"/>
    <link rel="stylesheet" href="~/lib/datatable/css/datatable.css">
    <link rel="stylesheet" href="~/lib/angular-datatables/css/angular-datatables.css">
    <link rel="stylesheet" href="~/lib/select2/dist/css/select2.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/admin.css" />

</head>
<body  ng-app="admin">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="nav-container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="brand" src="~/images/src/logo.png" /> <span>PERTAMINA</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"  ui-sref="home" ><a class="nav-link text-dark" >Home</a></li>
                        <li class="nav-item"  ui-sref="periode" ><a class="nav-link text-dark" >Periode</a></li>
                        <li class="nav-item"  ui-sref="jenis" ><a class="nav-link text-dark" >Jenis Pelanggaran</a></li>
                        <li class="nav-item"  ui-sref="perusahaan" ><a class="nav-link text-dark" >Perusahaan</a></li>
                        <li class="nav-item"  ui-sref="karyawan" ><a class="nav-link text-dark" >Karyawan</a></li>
                        <li class="nav-item"  ui-sref="pelanggaran-baru" ><a class="nav-link text-dark" >Pelanggaran Baru</a></li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
     <main role="main" >
            @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
            &copy; 2020 - Pertamin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/datatables.net/jquery.dataTables.js"></script>
    <script src="~/lib/Chartjs/Chart.js"></script>
      <script src="~/lib/animejs/anime.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/angularjs/angular.min.js"></script>
    <script src="~/lib/angular-datatables/angular-datatables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/select2/dist/js/select2.js" asp-append-version="true"></script>
    <script src="~/lib/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="~/js/services.js" asp-append-version="true"></script>
    <script src="~/js/ng-files.js" asp-append-version="true"></script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    <script src="~/js/swipe.js" asp-append-version="true"></script>
    <script src="~/lib/easyqrcodejs/dist/easy.qrcode.min.js"></script>
    <script src="~/lib/angular-locale.js"></script>
    <script src="~/lib/print-area/demo/jquery.PrintArea.js"></script>
    <script src="~/lib/gasparesganga-jquery-loading-overlay/dist/loadingoverlay.min.js"></script>
    <script>
        $.LoadingOverlay("show");
        $(document).ready(function(){
            $('[data-toggle=tooltip]').hover(function(){
                // on mouseenter
                $(this).tooltip('show');
            }, function(){
                // on mouseleave
                $(this).tooltip('hide');
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome5/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.3/signalr.min.js"></script-->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="nav-container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="brand" src="~/images/src/logo.png" /> <span>PERTAMINA</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Undian" asp-action="Index">Undian</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
        <footer class="border-top footer text-muted">
            &copy; 2020 - Pertamin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </footer>
    </main>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/lottiefiles/lottie-player/dist/lottie-player.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="~/lib/angularjs/angular.min.js"></script>
    <script src="~/js/services.js" asp-append-version="true"></script>
    <script src="~/js/app.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>